default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: chat_space_development

test:
  <<: *default
  database: chat_space_test

production:
  <<: *default
  database: chat_space_production
  username: chat_space
  password: <%= ENV['CHAT_SPACE_DATABASE_PASSWORD'] %>
